name: test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: "script"
        run: echo Hello
      - name: "test"
        uses: ./.github/actions/test
        with:
          test: "muhehe"
